spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  jpa:
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/blog
  mail:
    host: smtp.qq.com
    username: 2973925586@qq.com
    password: lxjfnxpnczsfdhee
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587
mybatis:
  type-aliases-package: com.example.junior.Entity
  mapper-locations: classpath:/mapper/*.xml


